name: Roadmap item
description: Add a Roadmap item.
about: A roadmap item is a high-level description of a desired outcome or goal in the project, defining the value to be delivered and assigning ownership for its execution.
title: "[Roadmap item]: "
labels: ["roadmap"]
projects: ["hyperledger/48"]
body:
  - type: textarea
    id: description
    attributes:
      label: Short Description
      description: A short description of the value we are building.
    validations:
      required: true
  - type: textarea
    id: value-statement
    attributes:
      label: Value statement
      description: A short paragraph describing our goal.
      placeholder: What is the successful end-state when this has been delivered? The value we want to deliver. If your goal starts with a verb (“launch”, “build”, “implement”, etc) you probably have an action, so reframe it to describe the outcome that you want (eg: “we want to enhance the privacy for our users when presenting proofs without reducing assurances for the verifier” is a better goal than “implement AnonCreds
    validations:
      required: true
  - type: input
    id: architect
    attributes:
      label: Architect
      placeholder: Name
    validations:
      required: false
  - type: input
    id: qa
    attributes:
      label: QA Member
      placeholder: Name
    validations:
      required: false
  - type: input
    id: owner
    attributes:
      label: Owner
      placeholder: Name
    validations:
      required: true
